export const INIT_APPLICATION = 'INIT_APPLICATION'

export const REQUEST_COLLECTION = 'REQUEST_COLLECTION'
export const RECEIVE_COLLECTION = 'RECEIVE_COLLECTION'

export const REQUEST_TAG_DATA = 'REQUEST_TAG_DATA'
export const RECEIVE_TAG_DATA = 'RECEIVE_TAG_DATA'

export const LABEL_IMAGES = 'LABEL_IMAGES'
export const UNLABEL_IMAGES = 'UNLABEL_IMAGES'

export const REQUEST_PROBS = 'REQUEST_PROBS'
export const RECEIVE_PROBS = 'RECEIVE_PROBS'
export const RESET_PROBS = 'RESET_PROBS'

export const RECEIVE_FEATURE_TYPES = 'RECEIVE_FEATURE_TYPES'
export const REQUEST_FEATURE_TYPES = 'REQUEST_FEATURE_TYPES'

//Settings
export const SET_THRESHOLDS = 'SET_THRESHOLDS'
export const SET_ACTIVE_FEATURE_TYPE = 'SET_ACTIVE_FEATURE_TYPE'

//UI
export const TOGGLE_SELECTED = 'TOGGLE_SELECTED'
export const CLEAR_SELECTED = 'CLEAR_SELECTED'
export const SWITCH_PANEL = 'SWITCH_PANEL'
export const INCREASE_IMAGE_SIZE = 'INCREASE_IMAGE_SIZE'
export const DECREASE_IMAGE_SIZE = 'DECREASE_IMAGE_SIZE'
export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

